image: node:latest

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'main'

stages:
  - checks

default:
  before_script:
    - npm install -g pnpm@5.18.9
    - pnpm recursive install
    - pnpm -w build

test:
  stage: checks
  script:
    - pnpm -w test

typecheck:
  stage: checks
  script:
    - pnpm -w lint:typecheck
