image: node:latest

cache:
  untracked: true
  paths:
    - ~/.pnpm-store

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'main'

stages:
  - setup
  - checks
  - build

default:
  before_script:
    - npm install -g pnpm@6.2.3

install:
  stage: setup
  script:
    - pnpm recursive install
    - pnpm -w build

test:
  stage: checks
  script:
    - pnpm -w test
  timeout: 3h

typecheck:
  stage: checks
  script:
    - pnpm -w lint:typecheck
  timeout: 3h

ui:
  stage: build
  script:
    - apt-get install zip
    - cd src/ui
    - zip -r bundle.zip build # Already built by the before_script
  artifacts:
    expire_in: 30 days
    paths:
      - src/ui/bundle.zip
