image: node:14

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'main'

stages:
  - checks
  - build

default:
  before_script:
    - export NODE_OPTIONS=--max_old_space_size=4096
    - npm install -g pnpm@6.2.3
    - pnpm recursive install
    - pnpm -w build

test:
  stage: checks
  script:
    - pnpm -w test
  timeout: 3h

eslint:
  stage: checks
  script:
    - pnpm -w lint:eslint
  timeout: 3h

typecheck:
  stage: checks
  script:
    - pnpm -w lint:typecheck
  timeout: 3h

ui:
  stage: build
  script:
    - apt-get update
    - apt-get install --yes zip
    - cd src/ui
    - zip -r bundle.zip build # Already built by the before_script
  artifacts:
    expire_in: 30 days
    paths:
      - src/ui/bundle.zip
