image: node:latest

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master' # Execute jobs when a new commit is pushed to master branch

stages:
  - ci

typecheck:
  stage: ci
  script:
    - npm install -g pnpm typescript
    - pnpm recursive install
    - pnpm -w lint:typecheck

test:
  stage: ci
  script:
    - npm install -g pnpm typescript
    - pnpm recursive install
    - pnpm -w test

build:
  stage: ci
  script:
    - npm install -g pnpm typescript
    - pnpm recursive install
    - pnpm -w build
